name: Update the preCICE doxygen
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * SAT'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -yyq install doxygen graphviz

      - name: Fetch - landing page
        uses: actions/checkout@v2
        with:
          path: landing

      - name: Fetch - develop
        uses: actions/checkout@v2
        with:
          repository: precice/precice
          ref: develop
          path: develop

      - name: Fetch - main
        uses: actions/checkout@v2
        with:
          repository: precice/precice
          ref: main
          path: main

      - name: Build doxygen - develop
        working-directory: develop
        run: doxygen

      - name: Build doxygen - main
        working-directory: main
        run: doxygen

      - name: Gather
        run: |
          mkdir -p public
          mv landing/index.html public
          mv develop/docs/source-code-documentation/html public/develop
          mv main/docs/source-code-documentation/html public/main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
